In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import sys
print(sys.executable)

c:\Users\lujim\miniconda3\envs\cmapss\python.exe

In [3]:
cols = ['unit', 'cycle'] \
     + [f'op_setting_{i}' for i in range(1, 4)] \
     + [f'sensor_{i}' for i in range(1, 22)]

df = pd.read_csv('../data/CMaps/train_FD001.txt',
                 sep=r'\s+', header=None, names=cols)

df.head()

,unit,cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [4]:
lifespans = df.groupby('unit')['cycle'].max()
lifespans

unit
1      192
2      287
3      179
4      189
5      269
      ...
96     336
97     202
98     156
99     185
100    200
Name: cycle, Length: 100, dtype: int64

In [5]:
df.groupby('unit')['cycle'].max()

unit
1      192
2      287
3      179
4      189
5      269
      ...
96     336
97     202
98     156
99     185
100    200
Name: cycle, Length: 100, dtype: int64

In [6]:
df[df['unit'] == 1].tail()

,unit,cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
187,1,188,-0.0067,0.0003,100.0,518.67,643.75,1602.38,1422.78,14.62,...,519.79,2388.23,8117.69,8.5207,0.03,396,2388,100.0,38.51,22.9588
188,1,189,-0.0006,0.0002,100.0,518.67,644.18,1596.17,1428.01,14.62,...,519.58,2388.33,8117.51,8.5183,0.03,395,2388,100.0,38.48,23.1127
189,1,190,-0.0027,0.0001,100.0,518.67,643.64,1599.22,1425.95,14.62,...,520.04,2388.35,8112.58,8.5223,0.03,398,2388,100.0,38.49,23.0675
190,1,191,-0.0000,-0.0004,100.0,518.67,643.34,1602.36,1425.77,14.62,...,519.57,2388.30,8114.61,8.5174,0.03,394,2388,100.0,38.45,23.1295
191,1,192,0.0009,-0.0000,100.0,518.67,643.54,1601.41,1427.20,14.62,...,520.08,2388.32,8110.93,8.5113,0.03,396,2388,100.0,38.48,22.9649

In [7]:
lifespans.min()
lifespans.max()

np.int64(362)

In [8]:
lifespans.min()
lifespans.max()

np.int64(362)

In [9]:
print(lifespans.min())
print(lifespans.max())

128
362

In [10]:
lifespans

unit
1      192
2      287
3      179
4      189
5      269
      ...
96     336
97     202
98     156
99     185
100    200
Name: cycle, Length: 100, dtype: int64

同一型号的发动机,寿命差了近三倍;如果按固定周期维护,定在 128 就对长寿发动机过度维修浪费钱,定得晚就让短命发动机带病上天。所以需要按每台发动机的实际状态预测寿命。